# Dependencies
plugins:          [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hello
tagline:          'A blog'
description:      'Stuff (probably) worth writing about.'
url:              http://wadidaw.me

author:
  name:           'Faza Fahleraz'
  email:          ffahleraz@gmail.com
  twitter:        https://twitter.com/ffahleraz
  github:         https://github.com/ffahleraz

paginate:         5

# Custom vars
version:          0.9

github:
  repo:           https://github.com/ffahleraz/ffahleraz.github.io
