# Dependencies
plugins:          [jekyll-paginate]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hello
tagline:          'A blog'
description:      'Stuff (probably) worth writing about.'
url:              http://wadidaw.me
baseurl:          /

author:
  name:           'Faza Fahleraz'
  url:            https://twitter.com/ffahleraz

paginate:         5

# Custom vars
version:          0.9

github:
  repo:           https://github.com/ffahleraz/ffahleraz.github.io
